#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Piano.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Piano.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Piano.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Piano.clap"
exit 0
